package com.ibm.dst.frame.jfinal.common.model;

import com.ibm.dst.frame.jfinal.common.model.base.BaseUSER;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class USER extends BaseUSER<USER> {
	public static final USER dao = new USER();
}
